# Generated by Django 3.2.8 on 2021-10-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passed_by',
            field=models.CharField(default='Nina', max_length=50),
        ),
    ]
