# Generated by Django 3.2.8 on 2021-10-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_passed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passed_by',
            field=models.CharField(max_length=50),
        ),
    ]
